src/ui/components/UserDefineDescription/index.tsx
added binding phrase detail regarding tranditional RX binding
=> add binding phrase detail -tranditional RX binding

src/api/src/services/Firmware/index.ts
This pull request implements the requested enhancement to give the generated firmware a meaningful name.
=> Generate a meaningful name for the firmware file

src/ui/components/DeviceTargetForm/index.tsx
This simplifies the device selection process by splitting the current target selection box into 2 separate selection boxes, the device category and device target.  With the addition of more targets, the current single selection box is continually growing in length and is making it more difficult for a user to find the targets for their device, by allowing the selection of the category separately from the target, it is easier for a user to find the target they need to select for their particular device.
=> Split device selection box into 2 separate select boxes, Device category and Device target

src/ui/components/DeviceTargetForm/index.tsx, src/ui/components/FlashingMethodOptions/index.tsx
This PR splits the current Device Target selection box into a device selection box and a list of radio buttons for the selection of the flashing method.  
Closes #38
=> Split the current target selection into device and flashing method.

src/ui/components/FirmwareVersionForm/index.tsx
=> Fix issue that after clicking "Back" button from the firmware flashing screen firmware options are not present anymore

devices.json, graphql.schema.json, src/api/src/models/Device.ts, src/api/src/models/enum/DeviceType.ts, src/api/src/services/Device/index.ts, src/api/src/services/Targets/index.ts, src/ui/App.tsx, src/ui/components/FirmwareVersionForm/index.tsx, src/ui/components/Sidebar/index.tsx, src/ui/components/WifiDeviceList/index.tsx, src/ui/components/WifiDeviceNotification/index.tsx, src/ui/components/WifiDeviceSelect/index.tsx, src/ui/gql/generated/types.ts, src/ui/gql/queries/availableFirmwareTargets.graphql, src/ui/hooks/useNetworkDevices.tsx, src/ui/storage/index.ts, src/ui/views/ConfiguratorView/index.tsx
Add support for building and flashing TX and VRX Backpacks.
=> Add support for building firmware from the backpack repository

src/ui/views/ConfiguratorView/index.tsx
=> Fix issue where an mdns record with no target will cause the wrong device to be selected

src/api/src/services/Targets/index.ts, src/ui/views/ConfiguratorView/index.tsx
- Show the target response errors on the UI
- Align local source target extraction to match GitHub sources
- Provide better error messages for local source target errors
=> Target errors

package.json, src/ui/App.tsx, yarn.lock
Upgrade react router to version 6
Closes #125
=> Upgrade to react router v6

devices.json, graphql.schema.json, src/api/src/models/enum/FlashingMethod.ts, src/ui/components/DeviceTargetForm/index.tsx, src/ui/components/FlashingMethodDescription/index.tsx, src/ui/components/FlashingMethodOptions/index.tsx, src/ui/gql/generated/types.ts, src/ui/views/ConfiguratorView/index.tsx
- Add radio flashing method
- Add radio targets to the Ghost transmitters - #76
=> Add radio flashing method

src/ui/components/SensitiveTextField/index.tsx, src/ui/components/UserDefinesList/index.tsx, src/ui/storage/index.ts
Remember if a user selected to show sensitive field data.
=> Persist show sensitive field data

devices/diy-2400.json, devices/jumper-2400.json
=> Add Jumper 2.4 GHz AIO Nano TX Module

src/ui/components/DeviceTargetForm/index.tsx
Sort the category and device drop downs alphabetically
=> Sort category and device drop downs

src/ui/components/FirmwareVersionForm/index.tsx
=> Add Release notes button

devices/rx5808-backpack.json
Add Backpack targets for RX5808_ESP01F_Backpack and RX5808_ESP01F_Diversity_Backpack which were added in ExpressLRS/Backpack#48
=> Add Rx5808 esp01f backpack targets

devices/vantac-2400.json
=> Add Vantac 2.4 GHz targets

.erb/configs/webpack.config.base.js, src/index.html, src/main.dev.ts, src/menu.ts, src/ui/components/Header/index.tsx
Set the application name based on entries in package.json instead of it being hard coded.
=> Set app name based on package.json

src/ui/components/UserDefineDescription/index.tsx
Mentioned here: https://discord.com/channels/596350022191415318/596350022191415320/951190446686756874
=> misleading text fixed

src/ui/components/UserDefineDescription/index.tsx
Reformat the REGULATORY_DOMAIN_EU_CE_2400 description so that it passes the prettier checks
=> Fix prettier issue with REGULATORY_DOMAIN_EU_CE_2400 description

devices/betafpv-2400.json, devices/diy-2400.json
=> Change RX24T to be an alias of BETAFPV 2400 RX

.eslintrc.js, .github/workflows/test.yml
Fix the test workflow so it can be used to detect issues when pull requests are submitted.
=> Fix The Test Workflow

package.json, src/api/src/services/SerialMonitor/index.ts, src/package.json, src/yarn.lock, yarn.lock
Upgrade the serialport library to 10.4.0
Closes #229
=> Upgrade serialport to 10.4.0

src/ui/hooks/useNetworkDevices.tsx
Don't add network device to the new devices list if it is already there and remove the device from the new devices list if a device removed event is received for it.
=> Network Device Monitor Update

devices/diy-2400.json
Reverts ExpressLRS/ExpressLRS-Configurator#309
=> Revert "add betafpv new rx flattie"

devices/betafpv-2400.json
this one has to be aligned with ELRS PR [1501](https://github.com/ExpressLRS/ExpressLRS/pull/1501)
=> rename betafpv nano target

src/ui/views/ConfiguratorView/index.tsx
=> Display error message when network device target can't be selected

devices/diy-2400.json, devices/radiomaster-2400.json
=> Migrate Radiomaster Zorro Internal TX from alias into a full target

devices/diy-backpack.json, devices/happymodel-backpack.json, graphql.schema.json, src/api/src/models/enum/FlashingMethod.ts, src/ui/components/FlashingMethodDescription/index.tsx, src/ui/gql/generated/types.ts, src/ui/views/ConfiguratorView/index.tsx
Add Passthrough flashing method and 2 new targets for Happy Model and DupleTX that use the new method
=> Add Passthrough flashing method and 2 new targets

devices/jumper-2400.json
Add the new Jumper T-Lite V2, which has internal ELRS.
=> Add Jumper T-Lite V2

devices/diy-2400.json
Adds the 6ch 2.4GHz PWMP. I think I did this right? I am not good at computers. Let me know if I am an idiot.
=> Add 2.4 DIY PWMPEX

devices/matek-2400.json
no big deal, just something I found while digging in the Skystars name mismatch
=> fixed a typo

devices/foxeer-2400.json
Add the Foxeer ESP8285 based RX with PA and RGB LED
=> Foxeer PA RGB RX target

devices/diy-2400.json
=> add Foxeer Lite 2400 Rx

devices/diy-2400.json
New target PR for BETAFPV uart AIO boards
=> BETAFPV AIO uart rx target

devices/betafpv-2400.json, devices/happymodel-2400.json
Use the SuperD specific PIO target as the SuperD has DCDC inductor.
=> Fix SuperD as it has DCDC

devices/radiomaster-2400.json
Adds support for the following targets
- Radiomaster Ranger
- Radiomaster Ranger Nano
- Radiomaster Ranger Micro
=> RadioMaster Ranger TX Modules

package.json, src/api/src/services/Firmware/index.ts
=> Sanitize the firmware filename

devices/hdzero-backpack.json
As it says, adds the HDZero goggle backpack.
Commit looks bigger because I fixed the formatting on the RX5.1 device as well.
=> Add HDZero goggle backpack target

.github/workflows/publish.yml, .github/workflows/test.yml
=> Actions: Update to Ubuntu 20.04

.github/workflows/publish.yml, .github/workflows/test.yml
Fixes https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/446
=> Fix deprecated set-output in Github Actions

devices/diy-900.json
To be added along with: https://github.com/ExpressLRS/ExpressLRS/pull/2219
=> Add DIY 900 STM32 SX1272 TX/RX PCB options

graphql.schema.json, src/api/src/graphql/inputs/BuildFlashFirmwareInput.ts, src/api/src/models/Device.ts, src/api/src/models/enum/BuildJobType.ts, src/api/src/services/BinaryFlashingStrategy/BinaryConfigurator/index.ts, src/api/src/services/BinaryFlashingStrategy/DeviceDescriptionsLoader/index.ts, src/api/src/services/FlashingStrategyLocator/BuildFlashFirmwareParams.ts, src/api/src/services/PlatformioFlashingStrategy/index.ts, src/ui/components/BuildProgressBar/index.tsx, src/ui/gql/generated/types.ts, src/ui/gql/queries/availableFirmwareTargets.graphql, src/ui/views/ConfiguratorView/index.tsx
=> Add erase and force flash as flashing options

src/main.dev.ts
Add an Unsupported OS message that notifies a user if they are using a Unsupported OS.
Closes #561
=> Unsupported OS Message

src/i18n/locales/en/messages.json, src/ui/components/DeviceOptionsForm/index.tsx, src/ui/components/FirmwareVersionForm/index.tsx, src/ui/hooks/useDeveloperMode.tsx, src/ui/storage/index.ts, src/ui/views/SettingsView/index.tsx
Closes #516 
This PR adds "developer mode" checkbox to the settings page.
| Developer mode | Configurator tabs | Device Options |
| ---------------- | ------------------ | ---------------- |
| ![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/14139027/78300dba-1ddf-4ff7-bd55-42c9bcaff473) | ![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/14139027/a649ec46-d13a-4a73-8f75-47d4a2d9dab0) | ![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/14139027/823f4409-2982-43d1-a278-3e374c8697cd) |
| ![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/14139027/70e1213a-837a-4257-9121-5969117b5fb3) | ![image](https://github.com/ExpressLRS/ExpressLRS-Configurator/assets/14139027/21cc3d3c-be8e-4af0-8bf6-5d7cc05d2c3b) | …
=> Implemet developer mode

src/i18n/locales/en/messages.json, src/i18n/locales/zh-CN/messages.json, src/i18n/locales/zh/messages.json, src/ui/views/ConfiguratorView/index.tsx
=> add "Flash again" button for massive flashing

package.json
=> Remove dependency on gconf2 for .deb package

src/i18n/locales.json
=> Fix typo in locales.json

.github/workflows/translations-pull-request.yml, src/i18n/locales.json, src/i18n/locales/pl/messages.json
I have added the messages.json file in locales/pl/, I have also added the polish language in src/i18n/locales.json and added '--language=pl' in .github/workflows/translations-pull-request.yml so that further retranslations get pulled automatically.
=> Added a translated polish version of the configurator

src/api/src/services/BinaryFlashingStrategy/DeviceDescriptionsLoader/index.ts
=> Remove UART_INVERTED option for all ESP32 based devices

src/ui/storage/commands/mergeWithDeviceOptionsFromStorage.ts, src/ui/storage/commands/persistDeviceOptions.ts, src/ui/storage/index.ts
=> Make binding phrase, wifi ssid & password settings global
