ExpressLRS/ExpressLRS-Configurator

src/api/src/services/Firmware/index.ts

Now firmware.bin will be moved into temporary system directory after successful build and this directory will be show for the user.
Closes #40 
Already tested only on MacOS.
I have to test it on Windows and possible Debian.

Open firmware.bin in a temp directory

---

src/ui/components/UserDefineDescription/index.tsx

This PR updates description text in tooltips for FEATURE_OPENTX_SYNC and FEATURE_OPENTX_SYNC_AUTOTUNE because of OpenTX 2.3.12 release. OpenTX 2.3.12 brings features which was required for flashing, but was only available in nightly OpenTX builds.
Closes #39

Update description text for FEATURE_OPENTX_SYNC

---

src/ui/components/Omnibox/index.tsx

This PR changes the way OmniBox handles the display of items when the user has not entered a search string.  Instead of passing the items through QuickScore with no search value, which results in a change to the original ordering of items, it displays the items in the order as they were passed in.  This solves an issue with the firmware version selector where the latest release was not being displayed first.

have OmniBox maintain the original item order if there is no search value

---

src/main.dev.ts

expresslrs-configurator.log is now selected when opening the logs folder
Closes #47

Fix issue with expresslrs-configurator.log not being selected when opening logs folder

---

src/ui/components/FirmwareVersionForm/index.tsx

The configurator remembers the last firmware that the user selected to assist the user in flashing the same firmware version to all their ExpressLRS hardware.  The downside to this is the user may not know when a new version of the firmware is available.  This PR adds an alert to notify the user if there is a newer version of the firmware than they currently have selected.  The alert is based on the currently selected filter, if "Show pre-releases" is not selected it will only alert about non RC releases, but will include RC releases when "Show pre-releases" is checked.

Newer Firmware Version Alert

---

graphql.schema.json
src/api/src/graphql/args/FirmwareVersionDataInput.ts
src/api/src/graphql/inputs/FirmwareVersionDataInput.ts
src/api/src/graphql/resolvers/Sources.resolver.ts
src/api/src/models/PullRequest.ts
src/api/src/models/enum/FirmwareSource.ts
src/api/src/services/Firmware/index.ts
src/api/src/services/GitHubClient/index.ts
src/api/src/services/UserDefinesBuilder/index.ts
src/ui/components/FirmwareVersionForm/index.tsx
src/ui/gql/generated/types.ts
src/ui/gql/queries/deviceOptions.graphql
src/ui/gql/queries/getPullRequests.graphql
src/ui/views/ConfiguratorView/index.tsx

This adds pull requests as a firmware source option.  A new tab is added under Firmware Version, Git Pull Request, which when selected will show a select box that shows the currently open pull requests from which you can choose.
Closes #43

Add Pull Request as a firmware source options

---

src/api/src/services/Firmware/index.ts

The ESP backpack WIFI update process requires the name of the firmware file to specifically be firmware.  This PR copies the firmware into the temp folder with the original name as well as the more meaningful name, which will allow users with those devices to perform a WIFI update without having to rename a file.
Closes #62

Copy the firmware file to the tmpPath with the original filename.

---

graphql.schema.json
src/api/index.ts
src/api/src/graphql/args/Lua.ts
src/api/src/graphql/resolvers/Lua.resolver.ts
src/api/src/models/LuaScript.ts
src/api/src/services/Lua/index.ts
src/ui/App.tsx
src/ui/components/BuildResponse/index.tsx
src/ui/gql/generated/types.ts
src/ui/gql/queries/luaScript.graphql
src/ui/views/ConfiguratorView/index.tsx

- Update the Lua script location logic to choose the latest version of the Lua script from the selected firmware source
- Make the Lua download button more visible by changing it to a contained button and also showing the button after a successful build of a TX firmware along with a notification message telling the user to update their Lua script #99
- Only show the retry button on an unsuccessful build and also make it retry the build type that was previously attempted instead of always executing build and flash.
- Update the build error message styling to make it more readable by specifying pre-wrap and using a monospace font family.

Lua, Retry, and Build Error Updates 

---

graphql.schema.json
src/api/src/factories/TargetUserDefinesFactory.ts
src/api/src/models/UserDefine.ts
src/api/src/models/enum/UserDefineOptionGroup.tsx
src/ui/components/DeviceOptionsForm/index.tsx
src/ui/gql/generated/types.ts
src/ui/gql/queries/deviceOptions.graphql
src/ui/storage/commands/mergeWithDeviceOptionsFromStorage.ts
src/ui/storage/commands/persistDeviceOptions.ts
src/ui/storage/index.ts

- Store WIFI settings at the global scope
- Store regulatory domain at the global scope.
To assist in the identification of the 900 MHz regulatory domains, a new property, UserDefineOptionGroup, was added to the UserDefine class to allow the grouping of the options.  The UI was also updated so that only one option in a UserDefineOptionGroup can be selected at a time.
Closes #91

Store regulatory domain and WIFI settings at the global scope

---

src/ui/components/FirmwareVersionForm/index.tsx

Fix issue of firmware releases not being properly sorted since the tag creation date is being used instead of the release version number. 
Closes #146

Sort releases by release version instead of the date created

---

devices/betafpv-2400.json
devices/betafpv-900.json
devices/diy-2400.json
graphql.schema.json
src/api/src/models/Device.ts
src/api/src/services/Device/index.ts
src/ui/gql/generated/types.ts
src/ui/gql/queries/availableFirmwareTargets.graphql
src/ui/views/ConfiguratorView/index.tsx

Add abbreviated name property to alias devices and use it to populate the DEVICE_NAME user define.
Closes #156

Add abbreviated name support to Device

---

src/ui/App.tsx
src/ui/components/Sidebar/index.tsx
src/ui/components/WifiDeviceNotification/index.tsx
src/ui/context/AppStateProvider.tsx
src/ui/hooks/useAppState.tsx
src/ui/layouts/MainLayout/index.tsx
src/ui/models/AppState.tsx
src/ui/models/enum/AppStatus.tsx
src/ui/views/ConfiguratorView/index.tsx
src/ui/views/LogsView/index.tsx
src/ui/views/SerialMonitorView/index.tsx
src/ui/views/SettingsView/index.tsx
src/ui/views/SupportView/index.tsx

- Add context to store application state, specifically current application status(whether it is busy or not)
- Disable WIFI device alerts during build/flash - Closes #196
- Use application status to determine whether navigation should be enabled in the side bar
- Refactor views to extract the header and sidebar into a common layout

Disable wifi device alerts during build

---

devices/betafpv-2400.json
devices/betafpv-900.json
devices/diy-2400.json
devices/diy-900.json
devices/frsky-900.json
devices/ghost-2400.json
devices/happymodel-2400.json
devices/happymodel-900.json
devices/jumper-900.json
devices/matek-2400.json
devices/namimnorc-2400.json
devices/namimnorc-900.json
devices/siyi-2400.json

Added new expresslrs.org URLs, when selecting various flash methods of some tx/rx hardware.
/trasmitters/ path added where missing in tx wiki URL
/receivers/ path added where missing in rx wiki URL

Fixed tx/rx wiki URL path

---

src/ui/views/ConfiguratorView/index.tsx

Current logic for matching a network device to a particular target uses startsWith, however this does not work when we have multiple devices that start with the same characters like MATEK_2400_RX and MATEK_2400_RX_PWM.  Change the matching logic to split the target name at "_via_" and check for an exact match.

Fix network device select issue

---

devices/betafpv-2400.json
devices/betafpv-900.json
devices/diy-2400.json
graphql.schema.json
src/api/src/models/Device.ts
src/api/src/services/Device/index.ts
src/ui/components/DeviceTargetForm/index.tsx
src/ui/gql/generated/types.ts
src/ui/gql/queries/availableFirmwareTargets.graphql

Add a warning that shows when a user selects a device that has not be verified to work correctly by the ExpressLRS developers.

Add warning about unverified hardware

---

devices/jumper-2400.json

This PR adds via ETXPassthrough flashing option for the Jumper TPro internal ExpressLRS module.
This is inline with the main Repo PR #1383

Adds via ETXPassthrough to Jumper T-Pro

---

src/api/src/library/FirmwareDownloader/index.ts
src/api/src/library/Platformio/index.ts

With the upgrade of the bundled python on Windows to 3.11.0a4, when spawning a PlatformIO process, the output is coming through the wrong output pipes and eventually filling up the buffer.  If PlatformIO is launched in a shell, the output of the process correctly comes through the expected stdout and stderr pipes and can be read as normal.

Launch PlatformIO in a shell

---

src/api/src/library/Mutex/index.ts
src/api/src/services/TargetsLoader/GitTargets.ts
src/api/src/services/UserDefinesLoader/GitUserDefinesLoader.ts

- Handle situation where src folder is at the root of the repo, like the Backpack repo.
- Add locking around access to the local git repos for targets and user defines to prevent multiple processes accessing/modifying the files at the same time. Closes #260 
- Fix Git Pull Request source in the user defines loader

Git based loading of target and user defines fixes

---

src/api/src/library/Platformio/index.ts

When spawning Platform IO using a shell, wrap the fully qualified path name in quotes so that spaces in the path do not cause an issue. 
Closes #275

Handle space in Platform IO executable path when using shell

---

.github/workflows/publish.yml

GitHub moved the windows-latest VM Environment to a Windows Server 2022 image which is causing issues with the build process, change to specifically use windows-2019.

Use windows-2019 for the windows build environment

---

graphql.schema.json
src/api/src/library/FirmwareBuilder/index.ts
src/api/src/library/Platformio/Enum/UploadType.ts
src/api/src/library/Platformio/index.ts
src/api/src/models/enum/BuildFirmwareErrorType.ts
src/api/src/models/enum/BuildJobType.ts
src/api/src/services/Firmware/index.ts
src/ui/components/BuildProgressBar/index.tsx
src/ui/components/BuildResponse/index.tsx
src/ui/components/SplitButton/index.tsx
src/ui/gql/generated/types.ts
src/ui/views/ConfiguratorView/index.tsx

- Add support for a new build type that allows force flashing a device when the new firmware target does not match the devices existing firmware target
- Change the current "Build & Flash" button to a split button with 2 options, "Build & Flash" and "Force Flash" ![image](https://user-images.githubusercontent.com/38869875/154565640-b06b7330-2dd3-4cbc-b992-d347c3ad5a89.png)
- When "Build & Flash" fails with a target mismatch error, show the "Force Flash" button. ![image](https://user-images.githubusercontent.com/38869875/154565903-786c4aa4-2143-4cf8-83c0-e260429c0efb.png)
Closes #250

Add Force Upload Support

---

src/main.dev.ts

This adds support for auto updating the configurator on Windows.  
MacOS requires the binaries to be signed, so we can't support auto updates for it yet.  There was a ticket opened for electron-builder to allow self signed certificates, but so far it has not got any traction https://github.com/electron-userland/electron-builder/issues/6378. 
The only build target that supports auto updating on Linux is AppImage, which we do not currently support as a installation method since it would necessitate bundling git and python in the image instead of letting the package manager handle the dependencies, but could be supported in the future.

Enable Electron Auto Updater on Windows

---

src/ui/components/ShowAfterTimeout/index.tsx
src/ui/views/ConfiguratorView/index.tsx

There seems to be a common problem of individuals unplugging their device too soon after a WIFI flash before the device has fully rebooted, which can cause the device to be soft bricked and stuck in a boot loop.  When flashing via the webpage, there is a delay in showing the success message to alleviate this issue, but this does not exist in the configurator.
After a successful WIFI flash, show a warning about unplugging the power to soon and delay the success message for 15 seconds to allow for the device to fully reboot.

Warn about unplugging power to soon when flashing via WIFI

---

src/ui/components/CardTitle/index.tsx
src/ui/views/ConfiguratorView/index.tsx

Add a button to the Logs card title that allows easy copying of the build log.

Add copy logs button

---

src/ui/components/BuildResponse/index.tsx
src/ui/views/ConfiguratorView/index.tsx

Including the stderr output of the build job in the build error alert is not very useful since it can contain extraneous data not relevant to the issue itself while also not containing enough contextual information to understand the actual cause of the issue.  Instead of including the stderr output, include a generic message directing the user to the documentation and to the help-and-support channel on discord.

Generic build error message

---

src/ipc/index.ts
src/main.dev.ts
src/ui/views/ConfiguratorView/index.tsx

Add a button to the Logs card title that allows saving of the build log to a file.

Add save build log

---

.eslintrc.js

No need to enforce linebreak styles since "* text=auto" in .gitattributes will ensure LF is committed to the repo

Disable Linebreak Style Rule

---

.eslintrc.js

Eslint will no longer warn for conole.error() but will still warn for console.log() and console.warn().
Addresses [Issue #289](https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/289).

Disable warn for console.error()

---

devices/namimnorc-2400.json
graphql.schema.json
src/api/index.ts
src/api/src/factories/TargetUserDefinesFactory.ts
src/api/src/models/Device.ts
src/api/src/models/UserDefineOverride.ts
src/api/src/services/Device/index.ts
src/api/src/services/UserDefinesBuilder/index.ts
src/ui/gql/generated/types.ts
src/ui/gql/queries/availableFirmwareTargets.graphql

Alter the userDefines array in the configuration file to be either a string or a UserDefineOverride object that provides the ability to change the default value of a user define.
To support device specific overrides of user defines, the DeviceService now fully builds out the user defines for each device and applies the overrides included in the configuration file, instead of just keeping a list of UserDefineKeys that the device supports.  The UserDefinesBuilder no longer needs the TargetUserDefinesFactory to generate the UserDefines since it can get them from the device object itself, so the TargetUserDefineFactory has been changed from being a service to a regular class that is used by the DeviceService.

Add ability to override user define default values in device configuration file

---

src/api/src/library/FirmwareDownloader/index.ts

If git repository directory is not empty and it is not a valid git repository, then remove the existing files.
Closes #315

Detect invalid git repository

---

devices/axis-2400.json
devices/axis-backpack.json
devices/betafpv-2400.json
devices/betafpv-900.json
devices/diy-2400.json
devices/diy-900.json
devices/frsky-900.json
devices/ghost-2400.json
devices/happymodel-2400.json
devices/happymodel-900.json
devices/jumper-2400.json
devices/jumper-900.json
devices/matek-2400.json
devices/namimnorc-2400.json
devices/namimnorc-900.json
devices/radiomaster-2400.json
devices/siyi-2400.json
devices/vantac-2400.json

With the update on the Docs via PR [#197](https://github.com/ExpressLRS/Docs/pull/197) as per issue #326 
I have updated each of the devices WikiURL properties.
I have tested the changes via local yarn start and the links resolve to the right links.
Do verify that is the case.
Let me know of any changes/corrections.

Update on Devices WikiURLs

---

src/api/src/services/MulticastDns/index.ts

mdns responses now doenst rely on the url starting with "elrs" and its now supporting multiple elrs answers in a response

refactoring mdns request parsing

---

devices/orqa-backpack.json

Add the option to target the FPV.Connect Backpack (https://github.com/ExpressLRS/Backpack/pull/70).
Can I just add a category for "Goggles" like this?

Added Orqa FPV.Connect ESP Backpack target

---

devices/happymodel-2400.json
devices/matek-2400.json

The RadioMaster RXes are actually called RP1 and RP2, so these have been updated.
Also added the new RP3 diversity RX.

Update RadioMaster RP1/2 and add RP3

---

devices/happymodel-2400.json
devices/namimnorc-2400.json

REGULATORY_DOMAIN_EU_CE_2400 was not included on the HM ES24TX Pro Series 2400 TX, NamimnoRC FLASH 2400 TX, and NamimnoRC FLASH 2400 OLED TX devices since they did not support 10mw.  REGULATORY_DOMAIN_EU_CE_2400 can now be added to those devices since v3 of the firmware includes support for LBT.  This will have the side effect of making this option available on older firmware which don't technically support it, but there is no easy way to solve for that.

Add REGULATORY_DOMAIN_EU_CE_2400 back to the TXs that didn't support 10mw

---

src/ui/App.tsx
src/ui/hooks/useBuildLogs.tsx
src/ui/hooks/useBuildProgressNotifications.tsx
src/ui/views/ConfiguratorView/index.tsx
yarn.lock

There is an issue with Apollo GraphQL subscriptions when used with React v18 in which a subscription cannot be subscribed to again, this is causing issues with the configurator view which is used for both the TX/RX and the backpack configuration and uses the progress notifications and build logs subscriptions.  This PR moves those subscriptions to the app layer and passes down the data to the view so it is not necessary to resubscribe to the subscriptions when the view changes.
See https://github.com/apollographql/apollo-client/issues/9664 for the Apollo issue.

Refactor progress notifications and build logs subscriptions

---

src/ui/components/UserDefineDescription/index.tsx

CE is now capped at 100mW (previously 10mW), and uses LBT.

Fix label for CE domain

---

devices/radiomaster-2400.json

This adds a Device Target on the Configurator for the TX12 with Internal ELRS  module.
It is an Alias of the Zorro Target, so it will build the Zorro binary.
They are essentially the same and is interchangeable. This PR aims to lessen user confusion by providing specific Device Target for the TX12, until Unified Targets are incorporated into the Configurator.

Adds TX12 Alias Target

---

devices/betafpv-2400.json
devices/diy-2400.json
devices/diy-900.json
devices/emax-2400.json
devices/emax-900.json

Adds new targets for 2 TX modules, 2.4GHZ and 900MHz.
Also add aliases for 3 RX devices. 2 x 2.4Ghz, a "plain jane" and a PA version, and one 900MHz "plain jane" version.

Add EMAX targets

---

src/ui/components/UserDefineDescription/index.tsx

- AUTO_WIFI_ON_INTERVAL was actually 30 in v1, and 60 as of v2 onwards 
- TLM_REPORT_INTERVAL_MS was 320LU in v2, and is now 240LU as of v3.
Also some minor rephrasing of these descrptions.
None of the other commonly shown defines after
looking at a few random TX/RX combos stood out
as needing any changes.

UserDefineDescription updates

---

devices/emax-2400.json
devices/emax-900.json

With adjustments to previous targets as they were introduced in 3.0 so some options didn't make sense

Add EMAX nano TX targets

---

devices/happymodel-2400.json

The HappyModel Slim Pro module has been broken for some time as it's actually just an alias for the regular pro series one and the firmware repo didn't actually have a target called `HappyModel_ES24TX_Slim_Pro_2400_TX_via_*`

The slim pro should be just an alias

---

devices/quadcopters-2400.json

Also with the QuadKopters Slim module it's an alias for the JR version.
They did however have a PIO target in the 1.1.x branch of the firmware repo, but it never got merged in 2.x or later 🤷‍♂️

The slim module is an alias for the JR module

---

devices/diy-2400.json

Adds the ER5 A/C as an alias for DIY PWMP5 target
Fixes #425

Add missing Radiomaster ER5 series receivers

---

src/ui/components/SerialConnectionForm/index.tsx
src/ui/components/SerialDeviceSelect/index.tsx

When React.Strict is specified, Apollo polling does not automatically start when a pollInterval is specified, startPolling must be explicitly called.
See issue https://github.com/apollographql/apollo-client/issues/9819

Fix React.Strict and Apollo polling issue

---

src/ui/components/FirmwareVersionForm/index.tsx
src/ui/config/index.ts

Currently the tag excludes only supports specifically listing the version that should be excluded from the list, this adds supports for using semantic versioning comparators.   For instance, if it is desired to exclude all versions prior to 2.5.0, this change allows it to be done by specifying "<2.5.0" instead of listing each version individually.

Add support for using semantic versioning comparators to exclude version ranges

---

README.md

PlatformIO release 6.1.6 made assets (templates, 99-platformio-udev.rules) part of Python's module (issue #4458).

Update PIO udev rules link

---

src/main.dev.ts

Fix: Check for non-ASCII before using dirtyPath

---

src/api/src/library/FirmwareBuilder/index.ts
src/api/src/services/Firmware/index.ts

After a build is completed, copy all *.elrs and *.bin files to the output directory.
Closes #479

Copy all elrs and bin files to the tmp output directory

---

devices/hdzero-backpack.json

With there already being a category for `Goggles` (containing the [`Orqa FPV.Connect ESP Backpack`](https://github.com/ExpressLRS/ExpressLRS-Configurator/blob/master/devices/orqa-backpack.json#L3)) this target should be moved there as well.

Categorize HDZero Goggle VRX Backpack as "Goggles"

---

devices/diy-2400.json

https://www.happymodel.cn/index.php/2021/12/29/happymodel-expresslrs-elrs-epw5-2-4ghz-5ch-pwm-rc-receiver-for-fixed-wing/
https://www.happymodel.cn/index.php/2023/01/10/happymodel-expresslrs-elrs-epw6-tcxo-2-4ghz-6ch-pwm-rc-receiver-for-fixed-wing-epw5-2-4ghz-replacement/

Adds Happymodel EPW5 and EPW6 targets

---

devices/happymodel-2400.json

I had someone ask me what target to use for their EP2 receiver and said they couldn't find it in the configurator. This renames "HappyModel EP 2400 RX" to "HappyModel EP1/2 2400 RX" to help with identification and match what is in the ELRS targets.json. It also could help someone with an "EP1 Dual" who might think "EP" is close enough? Probably not?

Rename HappyModel EP to EP1/2

---

devices/hdzero-backpack.json

Also remove RX5.1 from goggle target names.
Matches PR in backpack repo https://github.com/ExpressLRS/Backpack/pull/88

Remove the `.` from target names

---

src/api/src/services/BinaryFlashingStrategy/BinaryConfigurator/index.ts
src/api/src/services/BinaryFlashingStrategy/index.ts

This changes the binary flashing strategy and configurator to pass the parameters as they were intended.
i.e. When flashing a cloud build, do not pass the binary, let the flasher find it.
Also, for "stock" upload and "Build" only supply the output directory so the flasher can copy the output binaries to that folder.

Correctly call the flasher

---

src/ui/views/ConfiguratorView/index.tsx

When filtering the Wifi device selection list, examine the lua name as well as the prior target name.

---

src/api/src/services/BinaryFlashingStrategy/TargetsJSONLoader/index.ts

On version 3.0.1 and 3.0.0 there are some invalid config entries, check if the config object is valid before trying to set the type and frequency on the object.

Check if the read config is valid before setting type and frequency

---

src/@types/i18next.d.ts

Change the default namespace path to the new location for the translations

Fix i18next types default namespace path

---

src/api/src/services/BinaryFlashingStrategy/index.ts

Statement was checking for non-existent `BuildJobType` which caused an exception and so an error was displayed after a successful flash

Fix error after flashing

---

src/app/updater.ts
src/i18n/locales/en/messages.json
src/main.dev.ts

useTranslation() can not be used in the auto updater because it is called by the main process and is not part of the browser UI window.  Instead, initiate its own version of i18next using the system locale as the preferred language.
2 keys in the English messages.json were also corrected, they had an extraneous period at the end.  This change will affect the translations on crowdin since the key has changed.

Fix issue with Auto Updater and I18n

---

.husky/pre-commit
package.json
src/@types/bluejay-rtttl-parse.d.ts
src/@types/svg.d.ts
src/ui/components/BuildResponse/index.tsx
src/ui/components/Loader/index.tsx
src/ui/components/SerialConnectionForm/index.tsx
src/ui/components/ShowAfterTimeout/index.tsx
src/ui/components/WifiDeviceNotification/index.tsx
src/ui/views/ConfiguratorView/index.tsx
src/ui/views/SerialMonitorView/index.tsx
tsconfig.json

Explicitly run the typescript compiler against the code on pre-commit to catch any type errors.
Existing type errors in the code base have been fixed.

Add type checking to husky pre commit

---

src/ui/components/DeviceTargetForm/index.tsx

The device target form is selecting the wrong device if multiple devices have the same name.
Still needs testing to make sure that switching from using the name to the id doesn't inadvertently break anything.
Closes #557

Fix issue with Device Target Form

---

.gitignore

Update gitignore to include windows release files like ExpressLRS Configurator Setup.exe and latest.yml

Update gitignore to include windows release files

---

src/ui/views/SettingsView/index.tsx

Try to solve #604 
Sort language labels in "()" alphabetically except English, becaunse English has no "()" in locale json file.

Sort languages list alphabetically in settings screen

---

.github/workflows/translations-pull-request.yml
src/i18n/locales.json
src/i18n/locales/de/messages.json
src/i18n/locales/it/messages.json
src/i18n/locales/pt/messages.json

Add Portuguese language

---

src/api/src/services/BinaryFlashingStrategy/DeviceDescriptionsLoader/index.ts

Seems like during the transition to the separate targets repo we have lost the ability to load target definitions from a local repository. i always found that quite handy for messing around with diy hardware. 
This PR restores that functionality by checking if a local repo actually has the hardware folder present and the only then returning the local path.

use local targetsdata for local builds, fixes #580

---

src/ui/components/UserDefineDescription/index.tsx

https://www.thethingsnetwork.org/docs/lorawan/frequencies-by-country.html 404s. Correct link is https://www.thethingsnetwork.org/docs/lorawan/frequencies-by-country/

Fix broken LoRaWAN Link

---

src/i18n/locales/en/messages.json

"Flash your receiver with this option enabled and use it as a  ~~instead of your~~ TX module."

improve `RxAsTx` description text

---

src/ui/components/DeviceOptionsForm/index.tsx
src/ui/components/UserDefinesList/index.tsx
src/ui/storage/index.ts

Some user defines should be available in expert mode only

---

src/api/src/services/BinaryFlashingStrategy/index.ts

When building firmware from a local repository, the ELRS Configurator looks in that directory for hardware definitions; however, when passing the built firmware to 'binary_configurator.py' it will always set the hardware definition directory (the flag '--dir') to the ELRS Configurator's local data directory. This means that while the build step works, the flash step fails unexpectedly due to the inconsistent hardware definition files.
This change will only affect local builds and only if a hardware directory exists in the local firmware directory. The purpose of the change is to allow custom targets to work with the ELRS Configurator without needing to upstream new targets to the hardware git repository; therefore, this change is only meant for development/advanced users.

Fix local builds unable to flash custom targets
